### ISSUE TITLE
segfault while creating iterator from nullptr

### ISSUE THREAD

**Issue by drowned-robots** [kephir4eg/trie#4]
trie.h, line 819.
You need to check for nullptr in find_prefix():
`        if(output == nullptr)
            return iterator();
        return iterator(output);
`

You can grant me permission to push to your repo and I will push bugfix in a new branch.

Anyway thank you for awesome trie! In is really fast and user-friendly.

**Comment by kephir4eg** [comment]
Please, create a pull request with your changes, I usually welcome and accept them.
